"""Updates on the feedback table

Revision ID: 1e1e65399265
Revises: 8f3ebffa2186
Create Date: 2025-06-09 12:07:38.280688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1e1e65399265'
down_revision: Union[str, None] = '8f3ebffa2186'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('ratings', sa.Integer(), nullable=False))
    op.drop_column('feedback', 'rating')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('rating', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('feedback', 'ratings')
    # ### end Alembic commands ###
