"""updates

Revision ID: 45782c86c458
Revises: 2d677fcf0ee9
Create Date: 2025-05-27 16:21:49.104854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '45782c86c458'
down_revision: Union[str, None] = '2d677fcf0ee9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_items', 'product_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_constraint('order_items_ibfk_8', 'order_items', type_='foreignkey')
    op.drop_constraint('order_items_ibfk_7', 'order_items', type_='foreignkey')
    op.drop_constraint('order_items_ibfk_1', 'order_items', type_='foreignkey')
    op.create_foreign_key(None, 'order_items', 'products', ['product_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'order_items', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'order_items', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('payments', 'order_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'payments', 'orders', ['order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.alter_column('payments', 'order_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.create_foreign_key('order_items_ibfk_1', 'order_items', 'users', ['user_id'], ['id'])
    op.create_foreign_key('order_items_ibfk_7', 'order_items', 'orders', ['order_id'], ['id'])
    op.create_foreign_key('order_items_ibfk_8', 'order_items', 'products', ['product_id'], ['id'])
    op.alter_column('order_items', 'product_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
