"""updated order

Revision ID: 4ccd27eb7d54
Revises: 6eae3b381ce9
Create Date: 2025-05-29 11:56:32.906823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ccd27eb7d54'
down_revision: Union[str, None] = '6eae3b381ce9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('order_items_ibfk_2', 'order_items', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('order_items_ibfk_2', 'order_items', 'orders', ['order_id'], ['id'])
    # ### end Alembic commands ###
