"""updates

Revision ID: 6eae3b381ce9
Revises: 8533c61b69b2
Create Date: 2025-05-27 16:59:05.923704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6eae3b381ce9'
down_revision: Union[str, None] = '8533c61b69b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('order_items_ibfk_4', 'order_items', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('order_items_ibfk_4', 'order_items', 'orders', ['order_id'], ['id'])
    # ### end Alembic commands ###
