"""updates

Revision ID: 8533c61b69b2
Revises: e73afb43a468
Create Date: 2025-05-27 16:36:00.585824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8533c61b69b2'
down_revision: Union[str, None] = 'e73afb43a468'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('order_items_ibfk_3', 'order_items', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('order_items_ibfk_3', 'order_items', 'orders', ['order_id'], ['id'])
    # ### end Alembic commands ###
