"""Updates on the feedback table

Revision ID: 8e74453607c1
Revises: bca9de6a830f
Create Date: 2025-06-09 11:00:05.501818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e74453607c1'
down_revision: Union[str, None] = 'bca9de6a830f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('order_id', sa.Integer(), nullable=True))
    op.add_column('feedback', sa.Column('product_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'feedback', 'orders', ['order_id'], ['id'])
    op.create_foreign_key(None, 'feedback', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'feedback', type_='foreignkey')
    op.drop_constraint(None, 'feedback', type_='foreignkey')
    op.drop_column('feedback', 'product_id')
    op.drop_column('feedback', 'order_id')
    # ### end Alembic commands ###
