"""updated order table

Revision ID: b19bac433e01
Revises: fbaabeaa2d81
Create Date: 2025-05-27 15:00:36.444061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b19bac433e01'
down_revision: Union[str, None] = 'fbaabeaa2d81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('order_id', table_name='payments')
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=False)
    op.create_unique_constraint(None, 'payments', ['checkout_request_id'])
    op.drop_constraint('payments_ibfk_1', 'payments', type_='foreignkey')
    op.drop_column('payments', 'paid_at')
    op.drop_column('payments', 'mpesa_receipt')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('mpesa_receipt', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('payments', sa.Column('paid_at', mysql.DATETIME(), nullable=True))
    op.create_foreign_key('payments_ibfk_1', 'payments', 'orders', ['order_id'], ['id'])
    op.drop_constraint(None, 'payments', type_='unique')
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.create_index('order_id', 'payments', ['order_id'], unique=True)
    # ### end Alembic commands ###
