"""updates

Revision ID: c61550b09eb3
Revises: b19bac433e01
Create Date: 2025-05-27 15:15:25.806972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c61550b09eb3'
down_revision: Union[str, None] = 'b19bac433e01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('order_id', table_name='payments')
    op.create_foreign_key(None, 'payments', 'orders', ['order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_index('order_id', 'payments', ['order_id'], unique=True)
    # ### end Alembic commands ###
