"""updates

Revision ID: e73afb43a468
Revises: eb25bd744d10
Create Date: 2025-05-27 16:30:35.330683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e73afb43a468'
down_revision: Union[str, None] = 'eb25bd744d10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('order_items_ibfk_5', 'order_items', type_='foreignkey')
    op.add_column('orders', sa.Column('total_price', sa.Float(), nullable=False))
    op.drop_column('orders', 'total_amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('total_amount', mysql.FLOAT(), nullable=False))
    op.drop_column('orders', 'total_price')
    op.create_foreign_key('order_items_ibfk_5', 'order_items', 'orders', ['order_id'], ['id'])
    # ### end Alembic commands ###
