"""updates

Revision ID: eb25bd744d10
Revises: 45782c86c458
Create Date: 2025-05-27 16:29:46.700266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb25bd744d10'
down_revision: Union[str, None] = '45782c86c458'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('order_items_ibfk_6', 'order_items', type_='foreignkey')
    op.add_column('orders', sa.Column('delivery_address', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'delivery_address')
    op.create_foreign_key('order_items_ibfk_6', 'order_items', 'orders', ['order_id'], ['id'])
    # ### end Alembic commands ###
