"""updated order table

Revision ID: fbaabeaa2d81
Revises: f108d6437f59
Create Date: 2025-05-27 14:57:30.490843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fbaabeaa2d81'
down_revision: Union[str, None] = 'f108d6437f59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('order_items', sa.Column('total_amount', sa.Float(), nullable=False))
    # op.add_column('order_items', sa.Column('status', sa.String(length=120), nullable=True))
    # op.add_column('order_items', sa.Column('payment_status', sa.String(length=100), nullable=True))
    # op.add_column('order_items', sa.Column('mpesa_checkout_request_id', sa.String(length=200), nullable=True))
    # op.add_column('order_items', sa.Column('mpesa_transaction_id', sa.String(length=100), nullable=True))
    # op.add_column('order_items', sa.Column('created_at', sa.DateTime(), nullable=True))
    # op.add_column('order_items', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # op.create_index(op.f('ix_order_items_user_id'), 'order_items', ['user_id'], unique=False)
    # op.drop_constraint('order_items_ibfk_2', 'order_items', type_='foreignkey')
    # op.drop_constraint('order_items_ibfk_4', 'order_items', type_='foreignkey')
    # op.drop_constraint('order_items_ibfk_3', 'order_items', type_='foreignkey')
    # op.drop_column('order_items', 'quantity')
    # op.drop_column('order_items', 'product_id')
    # op.drop_column('order_items', 'order_id')
    # op.drop_column('order_items', 'price_per_item')
    # op.drop_index('order_id', table_name='payments')
    # op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    # op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=False)
    # op.create_unique_constraint(None, 'payments', ['checkout_request_id'])
    # op.drop_constraint('payments_ibfk_1', 'payments', type_='foreignkey')
    # op.drop_column('payments', 'mpesa_receipt')
    # op.drop_column('payments', 'paid_at')
    # # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('payments', sa.Column('paid_at', mysql.DATETIME(), nullable=True))
    # op.add_column('payments', sa.Column('mpesa_receipt', mysql.VARCHAR(length=100), nullable=True))
    # op.create_foreign_key('payments_ibfk_1', 'payments', 'orders', ['order_id'], ['id'])
    # op.drop_constraint(None, 'payments', type_='unique')
    # # op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    # # op.drop_index(op.f('ix_payments_id'), table_name='payments')
    # op.create_index('order_id', 'payments', ['order_id'], unique=True)
    # op.add_column('order_items', sa.Column('price_per_item', mysql.FLOAT(), nullable=False))
    # op.add_column('order_items', sa.Column('order_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    # op.add_column('order_items', sa.Column('product_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    # op.add_column('order_items', sa.Column('quantity', mysql.INTEGER(), autoincrement=False, nullable=False))
    # op.create_foreign_key('order_items_ibfk_3', 'order_items', 'users', ['user_id'], ['id'])
    # op.create_foreign_key('order_items_ibfk_4', 'order_items', 'orders', ['order_id'], ['id'])
    # op.create_foreign_key('order_items_ibfk_2', 'order_items', 'products', ['product_id'], ['id'])
    # op.drop_index(op.f('ix_order_items_user_id'), table_name='order_items')
    # op.drop_column('order_items', 'updated_at')
    # op.drop_column('order_items', 'created_at')
    # op.drop_column('order_items', 'mpesa_transaction_id')
    # op.drop_column('order_items', 'mpesa_checkout_request_id')
    # op.drop_column('order_items', 'payment_status')
    # op.drop_column('order_items', 'status')
    # op.drop_column('order_items', 'total_amount')
    # # ### end Alembic commands ###

# 